### ISSUE TITLE
Add more registers as devices

### ISSUE THREAD

**Issue by albinsunnanbo** [jackfagner/ThermIQ-Domoticz#4]

**Comment by albinsunnanbo** [comment]
PR #1, #2, #3

**Comment by jackfagner** [comment]
Thank you! Great job.

**Comment by albinsunnanbo** [comment]
You're welcome, I need a bit more monitoring and plan to tweak hot water production to low cost hours.

**Comment by jackfagner** [comment]
I have done so myself. Tip: set hot water start temp to 29 deg C to disable production during the day, and increase it to 50+ C during night to enforce production

**Comment by albinsunnanbo** [comment]
Thanks, I'll try that. I'll do some monitoring first to see how it behaves before I start to fiddle.
